@startuml
class Creator{
	+void : templateCreate()
}

class Product{

}

class ConcreteCreator{

}

class ConcreteProduct{

}

Creator -> Product : Create(インスタンス化はしない)
Creator <|-- ConcreteCreator
Product <|-- ConcreteProduct
ConcreteCreator -> ConcreteProduct : Create(インスタンス化する)
@enduml