@startuml
package Abstract {
	class Creator{
		+templateCreate() : void
	}

	class Product{

	}
}

package Concrete {
	class ConcreteCreator{

	}

	class ConcreteProduct{

	}
}


Creator -> Product : Use
Creator <|-- ConcreteCreator
Product <|-- ConcreteProduct
ConcreteCreator -> ConcreteProduct : Create
@enduml