@startuml
title クラス図
interface Aggregate{
	iterator() : Iterator
}
interface Iterator{
	hasNext() : bool
	next() : object
}
class ConcreteAggregate{
	+iterator() : Iterator
}
class ConcreteIterator{
	+hasNext() : bool
	+next() : object
}
class ConcreteElement{

}
Aggregate <|... ConcreteAggregate
Iterator <|... ConcreteIterator
Iterator <-o Aggregate
ConcreteAggregate o--> ConcreteElement
ConcreteIterator o-> ConcreteAggregate
@enduml