@startuml
abstract class Builder {

}
class Director {
	+builder : Builder
}
class ConcreteBuilder {

}
class Client{

}
Client o-> Director
Director o-> Builder
Builder <|-- ConcreteBuilder
Client -> ConcreteBuilder : Create
@enduml